#!/bin/bash

set -e
B=""
DIR=""

while getopts ":s:bh" opt; do
case $opt in
s)
  echo "Updating PGP keys"
      gpg --refresh-keys linux-design/ex3/shared/pubring.gpg 
echo "Synchronizing shared directory"
     sudo rsync -ipa linux-design/ex3/shared/ ~/stage/usr/local/shared/ --delete-excluded  
 
echo "Entering the chroot jail"
    DIR="$2"
    shift 2
    
  ;;
   
b)
   echo "b opt"    
   B="-b $@"	 

 ;;


h)
     echo "          welcome to help:
      enter-stage -s| <stagedir> [-b] [command [args...]]
       Enter chroot jail in <stagedir>, optionally with full initialization.
      enter-stage -h|	show this help "
 
  ;; 
  
:)
     echo " argument < > is misisng in -$OPTARG"
	 ;;
*)
   echo "Invalid option - $OPTARG!"
     ;;

  
  
  esac
  done
  if [[ "${B}" != "" ]]; then
     echo "---- enter contauer and do commands: ${B} ---"  
     sudo systemd-nspawn -D "${DIR}" "${B}" 
  else 
    sudo systemd-nspawn -D "${DIR}"
  fi
