#!/bin/bash

set -e

while getopts ":s:b:h" opt; do
case $opt in
s)
  echo "Updating PGP keys"
      gpg --refresh-keys linux-design/ex3/shared/pubring.gpg 
echo "Synchronizing shared directory"
     sudo rsync -pav linux-design/ex3/shared/ ~/stage/usr/local/shared/  
 
#echo "f..t...... keys/gentoo.asc"
echo "Entering the chroot jail"
    sudo systemd-nspawn -D "$2"
  
   ;;
   
b)
    sudo systemd-nspawn -D "$2"
    echo " execute  commands.. "
	i=3
	while [[ "$i" ]];do
	 ls
	  i+=1
	 done
  exit	 

 ;;


h)
     echo "          welcome to help:
      enter-stage -s| <stagedir> [-b] [command [args...]]
       Enter chroot jail in <stagedir>, optionally with full initialization.
      enter-stage -h|	show this help "
 
  ;; 
  
:)
     echo " argument < > is misisng in -$OPTARG"
	 ;;
*)
   echo "Invalid option - $OPTARG!"
     ;;

  
  
  esac
  done
